# **IBM HR DATASET PROJECT**

#### **Import the libraries which are needed.**

In [10]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

#### **Automated load of dataset.**

In [12]:
def load_data(file_path):
    df=pd.read_csv(file_path)
    return df
    
df=load_data("WA_Fn-UseC_-HR-Employee-Attrition.csv")
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

**Data Dictionary – IBM HR Analytics Employee Attrition Dataset**

| **Feature Name** | **Description** | **Statistical Data Type** |
|------------------|-----------------|---------------------------|
| **Age** | Age of the employee (in years) | Numerical (Continuous) |
| **Attrition** | Whether the employee left the company (Yes/No) | Categorical (Binary/Nominal) |
| **BusinessTravel** | Frequency of business travel | Categorical (Nominal) |
| **DailyRate** | Daily salary rate | Numerical (Continuous) |
| **Department** | Department where the employee works | Categorical (Nominal) |
| **DistanceFromHome** | Distance between home and workplace | Numerical (Continuous) |
| **Education** | Education level (1–5) | Categorical (Ordinal) |
| **EducationField** | Field of education | Categorical (Nominal) |
| **EmployeeCount** | Number of employees (constant value) | Numerical (Discrete) |
| **EmployeeNumber** | Unique employee identification number | Numerical (Discrete/Identifier) |
| **EnvironmentSatisfaction** | Satisfaction with work environment (1–4) | Categorical (Ordinal) |
| **Gender** | Employee gender | Categorical (Nominal) |
| **HourlyRate** | Hourly salary rate | Numerical (Continuous) |
| **JobInvolvement** | Level of job involvement (1–4) | Categorical (Ordinal) |
| **JobLevel** | Job level (1–5) | Categorical (Ordinal) |
| **JobRole** | Employee's job role | Categorical (Nominal) |
| **JobSatisfaction** | Job satisfaction level (1–4) | Categorical (Ordinal) |
| **MaritalStatus** | Marital status | Categorical (Nominal) |
| **MonthlyIncome** | Monthly salary | Numerical (Continuous) |
| **MonthlyRate** | Monthly salary rate | Numerical (Continuous) |
| **NumCompaniesWorked** | Number of companies worked for previously | Numerical (Discrete) |
| **Over18** | Whether employee is over 18 years old | Categorical (Binary/Nominal) |
| **OverTime** | Whether employee works overtime | Categorical (Binary/Nominal) |
| **PercentSalaryHike** | Percentage increase in salary | Numerical (Continuous) |
| **PerformanceRating** | Performance rating (3–4) | Categorical (Ordinal) |
| **RelationshipSatisfaction** | Satisfaction with workplace relationships (1–4) | Categorical (Ordinal) |
| **StandardHours** | Standard working hours (constant value) | Numerical (Discrete) |
| **StockOptionLevel** | Stock option level (0–3) | Categorical (Ordinal) |
| **TotalWorkingYears** | Total years of work experience | Numerical (Continuous) |
| **TrainingTimesLastYear** | Number of training sessions attended last year | Numerical (Discrete) |
| **WorkLifeBalance** | Work-life balance rating (1–4) | Categorical (Ordinal) |
| **YearsAtCompany** | Years worked at the company | Numerical (Continuous) |
| **YearsInCurrentRole** | Years spent in the current role | Numerical (Continuous) |
| **YearsSinceLastPromotion** | Years since last promotion | Numerical (Continuous) |
| **YearsWithCurrManager** | Years worked with the current manager | Numerical (Continuous) |

**Summary**

- **Total Features:** 35
- **Target Variable:** Attrition
- **Numerical Features:** 20
- **Categorical Features:** 15
- **Binary Features:** Attrition, Over18, OverTime
- **Ordinal Features:** Education, EnvironmentSatisfaction, JobInvolvement, JobLevel, JobSatisfaction, PerformanceRating, RelationshipSatisfaction, StockOptionLevel, WorkLifeBalance
- **Nominal Features:** BusinessTravel, Department, EducationField, Gender, JobRole, MaritalStatus

#### **Data preprocessing**

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [16]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [17]:
le=LabelEncoder()

In [18]:
cols=["Attrition","BusinessTravel","Department","EducationField","Gender","JobRole","MaritalStatus","Over18","OverTime"]
for col in cols:
    df[col]=le.fit_transform(df[col])
print(le.classes_)

['No' 'Yes']

In [20]:
print(df["StandardHours"].unique())
print(df["Over18"].unique())
print(df["EmployeeCount"].unique())

[80]
[0]
[1]

In [27]:
df=df.drop(["StandardHours","Over18","EmployeeCount"],axis=1)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   int32
 2   BusinessTravel            1470 non-null   int32
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   int32
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   int32
 8   EmployeeNumber            1470 non-null   int64
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1470 non-null   int32
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobRole                   1470 non-null   int32
 15  JobSatisfaction           1470 non-null   int64
 16  MaritalStatus             1470 non-null   int32
 17  MonthlyIncome             1470 non-null   int64
 18  MonthlyRate               1470 non-null   int64
 19  NumCompaniesWorked        1470 non-null   int64
 20  OverTime                  1470 non-null   int32
 21  PercentSalaryHike         1470 non-null   int64
 22  PerformanceRating         1470 non-null   int64
 23  RelationshipSatisfaction  1470 non-null   int64
 24  StockOptionLevel          1470 non-null   int64
 25  TotalWorkingYears         1470 non-null   int64
 26  TrainingTimesLastYear     1470 non-null   int64
 27  WorkLifeBalance           1470 non-null   int64
 28  YearsAtCompany            1470 non-null   int64
 29  YearsInCurrentRole        1470 non-null   int64
 30  YearsSinceLastPromotion   1470 non-null   int64
 31  YearsWithCurrManager      1470 non-null   int64
dtypes: int32(8), int64(24)
memory usage: 321.7 KB

### **AUTOMATED TRAIN TEST SPLIT**

In [32]:
def split_features(df,target):
    X=df.drop(target,axis=1)
    y=df[target]
    return X,y
X,y=split_features(df,"Attrition")

In [34]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

#### **Fit the model.**
#### **Our model: Random Forest Classifier**

In [37]:
rf=RandomForestClassifier(n_estimators=200,random_state=42)
rf.fit(x_train,y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [39]:
y_pred=rf.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

#### **Model Evaluation**

In [42]:
y_pred=rf.predict(x_test)

print("\nAccuracy:")
print(accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy:
0.8741496598639455

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.99      0.93       255
           1       0.67      0.10      0.18        39

    accuracy                           0.87       294
   macro avg       0.77      0.55      0.55       294
weighted avg       0.85      0.87      0.83       294


Confusion Matrix:
[[253   2]
 [ 35   4]]

#### **Feature Importance Analysis.**

In [45]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print(importance)

                     Feature  Importance
16             MonthlyIncome    0.082529
19                  OverTime    0.064434
0                        Age    0.056851
2                  DailyRate    0.050766
24         TotalWorkingYears    0.048768
17               MonthlyRate    0.046778
7             EmployeeNumber    0.046303
27            YearsAtCompany    0.043594
10                HourlyRate    0.043386
4           DistanceFromHome    0.041976
18        NumCompaniesWorked    0.034643
20         PercentSalaryHike    0.032955
23          StockOptionLevel    0.031341
13                   JobRole    0.029648
30      YearsWithCurrManager    0.028920
15             MaritalStatus    0.027088
29   YearsSinceLastPromotion    0.026595
8    EnvironmentSatisfaction    0.026087
28        YearsInCurrentRole    0.025887
14           JobSatisfaction    0.025752
25     TrainingTimesLastYear    0.025047
26           WorkLifeBalance    0.022253
12                  JobLevel    0.021293
6             EducationField    0.021289
11            JobInvolvement    0.020481
5                  Education    0.019161
22  RelationshipSatisfaction    0.017715
3                 Department    0.013623
1             BusinessTravel    0.012213
9                     Gender    0.008204
21         PerformanceRating    0.004421

#### **Predict High-Risk Attrition**

In [48]:
y_pred= rf.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
results=x_test.copy()
results["Actual_Attrition"]=y_test.values
results["Predicted_Attrition"]=y_pred

In [56]:
results.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,...,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Actual_Attrition,Predicted_Attrition
1041,28,2,866,2,5,3,3,1469,4,1,...,0,6,4,3,5,4,1,3,0,0
184,53,2,1084,1,13,2,3,250,4,0,...,2,5,3,3,4,2,1,3,0,0
1222,24,2,240,0,22,1,0,1714,4,1,...,1,1,2,3,1,0,0,0,1,0
67,45,2,1339,1,7,3,1,86,2,1,...,1,25,2,3,1,0,0,0,0,0
220,36,2,1396,1,5,2,1,304,4,1,...,0,16,3,4,13,11,3,7,0,0

In [60]:
results["Risk_Level"]= results["Predicted_Attrition"].map({0:"Low risk",1:"High risk"})

In [62]:
results.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,...,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Actual_Attrition,Predicted_Attrition,Risk_Level
1041,28,2,866,2,5,3,3,1469,4,1,...,6,4,3,5,4,1,3,0,0,Low risk
184,53,2,1084,1,13,2,3,250,4,0,...,5,3,3,4,2,1,3,0,0,Low risk
1222,24,2,240,0,22,1,0,1714,4,1,...,1,2,3,1,0,0,0,1,0,Low risk
67,45,2,1339,1,7,3,1,86,2,1,...,25,2,3,1,0,0,0,0,0,Low risk
220,36,2,1396,1,5,2,1,304,4,1,...,16,3,4,13,11,3,7,0,0,Low risk